# Generated by Django 6.0.6 on 2026-07-15 19:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_purchase_bill_and_cloth_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('category', models.CharField(choices=[('UTILITIES', 'Utilities (Electricity / Water)'), ('RENT', 'Rent'), ('MAINTENANCE', 'Machine / Equipment Maintenance'), ('TRANSPORT', 'Transport / Delivery'), ('PACKAGING', 'Packaging Material'), ('LABOR', 'Contract Labour'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField()),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, help_text='Bill no / voucher / receipt ref', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='warehouse.warehouselocation')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
