# Generated by Django 6.0.8 on 2026-08-14 19:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_hsn_gst_split_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST rate % applicable to this item type (0 / 5 / 12 / 18 / 28)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
