# Generated by Django 6.0.8 on 2026-08-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_itemtype_gst_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='print_bank_details',
            field=models.TextField(blank=True, help_text='Bank account details printed at bottom of invoices/quotations'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='print_company_address',
            field=models.TextField(blank=True, help_text='Address shown on printed documents'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='print_show_logo',
            field=models.BooleanField(default=True, help_text='Show company logo on printed documents'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='print_signature_label',
            field=models.CharField(blank=True, default='Authorised Signatory', help_text='Label under signature line', max_length=80),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='print_terms',
            field=models.TextField(blank=True, default='All disputes subject to local jurisdiction.', help_text='Terms & conditions printed on documents'),
        ),
    ]
