# Generated by Django 6.0.8 on 2026-08-15 20:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_custom_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='gst_on_purchases',
            field=models.BooleanField(default=False, help_text='Apply GST on purchase bills (Input Tax Credit)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='gstin',
            field=models.CharField(blank=True, help_text='Company GSTIN — printed on purchase bills', max_length=15),
        ),
    ]
