# Generated by Django 6.0.8 on 2026-08-17 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_gst_on_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='readymadestock',
            name='cloth_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readymade_stocks', to='warehouse.clothcategory'),
        ),
    ]
