# Generated by Django 6.0.8 on 2026-08-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_readymadestock_cloth_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingassignment',
            name='age_group',
            field=models.CharField(blank=True, choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('BOYS', 'Boys'), ('GIRLS', 'Girls'), ('INFANT', 'Infant / Baby'), ('UNISEX', 'Unisex')], max_length=10),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='age_group',
            field=models.CharField(blank=True, choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('BOYS', 'Boys'), ('GIRLS', 'Girls'), ('INFANT', 'Infant / Baby'), ('UNISEX', 'Unisex')], max_length=10),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='age_group',
            field=models.CharField(blank=True, choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('BOYS', 'Boys'), ('GIRLS', 'Girls'), ('INFANT', 'Infant / Baby'), ('UNISEX', 'Unisex')], max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='age_group',
            field=models.CharField(blank=True, choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('BOYS', 'Boys'), ('GIRLS', 'Girls'), ('INFANT', 'Infant / Baby'), ('UNISEX', 'Unisex')], max_length=10),
        ),
        migrations.AddField(
            model_name='readymadestock',
            name='age_group',
            field=models.CharField(blank=True, choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('BOYS', 'Boys'), ('GIRLS', 'Girls'), ('INFANT', 'Infant / Baby'), ('UNISEX', 'Unisex')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stitchingjob',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing / Stitching'), ('QC_CHECK', 'Quality Check'), ('READY', 'Ready'), ('REJECTED', 'Rejected / Rework'), ('MOVED', 'Moved to Finished Goods')], default='RECEIVED', max_length=20),
        ),
    ]
