# Generated by Django 6.0.8 on 2026-08-20 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_expense_payment_method_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='source_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bills', to='warehouse.purchaseorder'),
        ),
    ]
