# Generated by Django 6.0.8 on 2026-08-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_purchase_bill_source_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='tag_brand_name',
            field=models.CharField(blank=True, help_text='Brand name on tags (defaults to company name)', max_length=80),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_footer_text',
            field=models.CharField(blank=True, help_text="Footer text on tags (e.g. '100% Cotton · Made in India')", max_length=120),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_printer_width',
            field=models.CharField(default='58mm', help_text='Thermal paper width: 58mm or 80mm', max_length=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_show_age_group',
            field=models.BooleanField(default=True, help_text='Show age group on printed tags'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_show_barcode',
            field=models.BooleanField(default=True, help_text='Show barcode on printed tags'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_show_color',
            field=models.BooleanField(default=True, help_text='Show cloth color on printed tags'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_show_sku',
            field=models.BooleanField(default=True, help_text='Show SKU code on printed tags'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_tagline',
            field=models.CharField(blank=True, help_text='Tagline under brand name on tags', max_length=120),
        ),
    ]
