# Generated by Django 6.0.8 on 2026-08-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_tag_layout_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(max_length=128),
        ),
    ]
