# Generated by Django 6.0.8 on 2026-08-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_hash_otp_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='status',
            field=models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('PARTIAL', 'Partially Paid'), ('SETTLED', 'Fully Settled'), ('OVERDUE', 'Overdue')], db_index=True, default='OUTSTANDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('STORE_KEEPER', 'Store Keeper'), ('CUTTING_MASTER', 'Cutting Master'), ('TAILOR', 'Tailor / Maker'), ('AUDITOR', 'Auditor (Read-only)')], db_index=True, default='STORE_KEEPER', max_length=50),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('RESET_PASSWORD', 'Reset Password')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='rawclothbatch',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
