# Generated by Django 6.0.8 on 2026-08-22 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0023_alter_credittransaction_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='creditpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='creditpayment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='salesorderitem_quantity_positive'),
        ),
    ]
