# Generated by Django 6.0.8 on 2026-08-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0024_creditpayment_creditpayment_amount_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='payment_number',
            field=models.CharField(default='', editable=False, max_length=40, unique=True),
        ),
    ]
