# Generated by Django 6.0.8 on 2026-08-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0025_add_credit_payment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='tag_brand_font_size',
            field=models.IntegerField(default=14, help_text='Brand name font size on tag (pt)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_component_order',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of tag component keys'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_logo_data',
            field=models.TextField(blank=True, help_text='Base64 logo for tags (b&w, small)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_logo_size',
            field=models.IntegerField(default=30, help_text='Logo height on tag (px)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_show_price',
            field=models.BooleanField(default=True, help_text='Show sale price on printed tags'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_show_size',
            field=models.BooleanField(default=True, help_text='Show size on printed tags'),
        ),
    ]
