# Generated by Django 6.0.8 on 2026-08-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0026_add_tag_designer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='tag_height_mm',
            field=models.IntegerField(default=80, help_text='Tag print area height in mm (white section only)'),
        ),
    ]
