# Generated by Django 6.0.8 on 2026-08-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0027_add_tag_height_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='tag_width_mm',
            field=models.IntegerField(default=54, help_text='Tag print area width in mm (white section only)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='tag_height_mm',
            field=models.IntegerField(default=65, help_text='Tag print area height in mm (white section only)'),
        ),
    ]
