# Generated by Django 6.0.8 on 2026-08-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0028_add_tag_width_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='tag_align',
            field=models.CharField(default='left', help_text='Tag text alignment: left, center or right', max_length=6),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_barcode_height_mm',
            field=models.FloatField(default=18.0, help_text='Barcode height on tag (mm)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_barcode_text_font_size',
            field=models.FloatField(default=8.5, help_text='Barcode number font size (pt)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_desc_font_size',
            field=models.FloatField(default=8.0, help_text='Colour / size font size (pt)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_gap_mm',
            field=models.FloatField(default=1.2, help_text='Vertical gap between tag rows (mm)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_name_font_size',
            field=models.FloatField(default=12.0, help_text='Item name font size (pt)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_pad_bottom',
            field=models.FloatField(default=3.0, help_text='Tag bottom padding (mm)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_pad_left',
            field=models.FloatField(default=13.0, help_text='Tag left padding (mm) — clears the foil strip'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_pad_right',
            field=models.FloatField(default=1.5, help_text='Tag right padding (mm)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_pad_top',
            field=models.FloatField(default=3.0, help_text='Tag top padding (mm)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_price_font_size',
            field=models.FloatField(default=12.0, help_text='MRP font size (pt)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_sku_font_size',
            field=models.FloatField(default=6.5, help_text='SKU font size (pt)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_vertical_align',
            field=models.CharField(default='center', help_text='Vertical placement: top, center or bottom', max_length=8),
        ),
    ]
