# Generated by Django 6.0.8 on 2026-08-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0029_systemsettings_tag_align_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PLACED', 'Placed'), ('DISPATCHED', 'Dispatched'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received'), ('VERIFIED', 'Verified'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
