# Generated by Django 6.0.8 on 2026-08-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0030_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='previous_barcodes',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
