# Generated by Django 6.0.8 on 2026-09-01 11:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0031_finishedproduct_previous_barcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='photos',
            field=models.TextField(blank=True, help_text='Comma-separated photo paths of the item ordered'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='dispatch_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='dispatch_photos',
            field=models.TextField(blank=True, help_text='Comma-separated photo paths of the loaded parcel / LR copy'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='freight_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='lr_number',
            field=models.CharField(blank=True, help_text='Lorry receipt / consignment note number', max_length=60),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
