# Generated by Django 6.0.8 on 2026-09-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0033_tag_rows_and_price_barcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='barcode_prefix_digits',
            field=models.PositiveSmallIntegerField(default=3, help_text='Random digits before the price in a product barcode (0-6)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='barcode_suffix_digits',
            field=models.PositiveSmallIntegerField(default=3, help_text='Random digits after the price in a product barcode (0-6)'),
        ),
    ]
