# Generated by Django 6.0.8 on 2026-09-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0035_numeric_price_barcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='barcode_price_source',
            field=models.CharField(choices=[('COST', 'Cost price'), ('SALE', 'Sale price')], default='COST', help_text='Which price is buried in a product barcode. Cost keeps a figure the customer cannot read off the tag; the sale price is already printed on it.', max_length=10),
        ),
    ]
