# Generated by Django 6.0.8 on 2026-09-02 05:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0037_barcode_carries_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='barcode_price_multiplier',
            field=models.DecimalField(decimal_places=3, default=Decimal('2.1'), help_text='Cost is multiplied by this before going into the barcode, so the figure does not read as a price. Divide by it to get the cost back.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='barcode_prefix_digits',
            field=models.PositiveSmallIntegerField(default=2, help_text='Random digits before the price in a product barcode (0-6)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='barcode_suffix_digits',
            field=models.PositiveSmallIntegerField(default=1, help_text='Random digits after the price in a product barcode (0-6)'),
        ),
    ]
