# Generated by Django 6.0.8 on 2026-09-02 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0039_disguised_price_barcodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='warehouse.finishedproduct')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('finished_product', 'name')},
            },
        ),
    ]
