# Generated by Django 6.0.8 on 2026-09-02 06:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0040_finishedproductoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Who or what is paid — 'Ravi (tailor)', 'Godown rent'", max_length=150)),
                ('kind', models.CharField(choices=[('SALARY', 'Salary'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='Day the payment is due. Clamped to the last day in short months.')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='warehouse.employeeprofile')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_settlements', to='warehouse.warehouselocation')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('SALARY', 'Salary'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.DateField(help_text='First day of the month this belongs to')),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('NEFT', 'NEFT / IMPS'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement', to='warehouse.expense')),
                ('recurring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='warehouse.recurringsettlement')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='warehouse.warehouselocation')),
            ],
            options={
                'ordering': ['-period', 'kind', 'name'],
                'constraints': [models.UniqueConstraint(fields=('recurring', 'period'), name='one_settlement_per_template_per_month')],
            },
        ),
    ]
