# Generated by Django 6.0.8 on 2026-09-02 06:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0041_recurringsettlement_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces_per_set', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='finished_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='warehouse.finishedproduct'),
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('name', models.CharField(help_text='e.g. Sherwani set 34-46', max_length=150)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Complete sets in stock')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('barcode', models.CharField(editable=False, max_length=60, unique=True)),
                ('barcode_svg', models.TextField(blank=True)),
                ('previous_barcodes', models.TextField(blank=True, editable=False)),
                ('tags_printed', models.BooleanField(default=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_sets', to='warehouse.itemtype')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_sets', to='warehouse.warehouselocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='product_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='warehouse.productset'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_product__isnull', False), ('product_set__isnull', True)), models.Q(('finished_product__isnull', True), ('product_set__isnull', False)), _connector='OR'), name='salesorderitem_product_or_set'),
        ),
        migrations.AddField(
            model_name='productsetitem',
            name='finished_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set_items', to='warehouse.finishedproduct'),
        ),
        migrations.AddField(
            model_name='productsetitem',
            name='product_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.productset'),
        ),
        migrations.AlterUniqueTogether(
            name='productsetitem',
            unique_together={('product_set', 'finished_product')},
        ),
    ]
