# Generated by Django 6.0.8 on 2026-09-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0042_productsetitem_alter_salesorderitem_finished_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='name',
            field=models.CharField(blank=True, help_text='Overrides the item type name on tags and listings. Blank uses the item type name.', max_length=200),
        ),
    ]
