# Generated by Django 6.0.8 on 2026-09-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0043_finishedproduct_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='tag_color_label',
            field=models.CharField(default='Color', help_text='Word before the colour on a tag. Blank prints the colour alone.', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_price_label',
            field=models.CharField(default='MRP', help_text='Word before the price on a tag, e.g. "MRP" or "Price". Blank prints the price alone.', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_price_suffix',
            field=models.CharField(default='/-', help_text='Printed after the price, e.g. "/-". Blank prints nothing after it.', max_length=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tag_size_label',
            field=models.CharField(default='Size', help_text='Word before the size on a tag. Blank prints the size alone.', max_length=20),
        ),
    ]
