# Generated by Django 6.0.8 on 2026-09-03 08:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0044_systemsettings_tag_color_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsite_id', models.PositiveIntegerField(help_text="The retail subsite's id. Every dispatch is pinned to this one.")),
                ('subsite_name', models.CharField(help_text="The subsite's handle, e.g. sriweddings — for display and for confirming the id.", max_length=64)),
                ('api_url', models.URLField(help_text='The retail GraphQL endpoint.')),
                ('service_username', models.CharField(blank=True, max_length=150)),
                ('service_password', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='retailchannel_is_a_singleton')],
            },
        ),
        migrations.CreateModel(
            name='RetailProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(help_text='Product id on the retail side.')),
                ('variant_id', models.PositiveIntegerField(blank=True, help_text='Variant id on the retail side, when the product has variants.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retail_link', to='warehouse.finishedproduct')),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_links_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetailStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.PositiveIntegerField(help_text="The store's building id on the retail side.")),
                ('name', models.CharField(help_text="The store's name, mirrored here so a dispatch reads sensibly.", max_length=140)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='warehouse.retailchannel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RetailDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PACKED', 'Packed'), ('SENT', 'Sent'), ('ACKNOWLEDGED', 'Acknowledged'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('transporter_name', models.CharField(blank=True, max_length=140)),
                ('lr_number', models.CharField(blank=True, max_length=60)),
                ('vehicle_number', models.CharField(blank=True, max_length=30)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('photos', models.TextField(blank=True, help_text='Comma-separated photo paths of the loaded consignment')),
                ('notes', models.TextField(blank=True)),
                ('receipt_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_dispatches_created', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_dispatches', to='warehouse.warehouselocation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='warehouse.retailstore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetailDispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Pieces this line is sending.')),
                ('packed_quantity', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost at the moment of dispatch, sent as goods-in cost.', max_digits=10)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.retaildispatch')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_dispatch_items', to='warehouse.finishedproduct')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dispatch', 'finished_product'), name='retaildispatchitem_one_line_per_product')],
            },
        ),
        migrations.AddConstraint(
            model_name='retailstore',
            constraint=models.UniqueConstraint(fields=('channel', 'building_id'), name='retailstore_unique_building'),
        ),
    ]
