# Generated by Django 6.0.8 on 2026-09-03 09:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0045_retailchannel_retailproductlink_retailstore_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('reason', models.CharField(choices=[('UNSOLD', 'Unsold / season over'), ('DAMAGED', 'Damaged'), ('WRONG_ITEM', 'Wrong item sent'), ('OTHER', 'Other')], default='UNSOLD', max_length=20)),
                ('restock', models.BooleanField(default=True, help_text='Off for goods that came back unsellable — they are recorded, not restocked.')),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_returns_received', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='warehouse.retailstore')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_returns', to='warehouse.warehouselocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetailReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_return_items', to='warehouse.finishedproduct')),
                ('retail_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.retailreturn')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('retail_return', 'finished_product'), name='retailreturnitem_one_line_per_product')],
            },
        ),
    ]
