# Generated by Django 6.0.8 on 2026-09-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0047_colour_is_its_own_tag_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawclothbatch',
            name='design_number',
            field=models.CharField(blank=True, db_index=True, help_text='The design number this cloth is known by', max_length=60),
        ),
        migrations.AddField(
            model_name='rawclothbatch',
            name='photos',
            field=models.TextField(blank=True, help_text='Comma-separated photo paths of the cloth'),
        ),
    ]
