# Generated by Django 6.0.8 on 2026-09-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0048_rawclothbatch_design_number_rawclothbatch_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebillitem',
            name='design_number',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
