# Generated by Django 6.0.8 on 2026-09-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0049_purchasebillitem_design_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stitchingjob',
            name='customer_bill_number',
            field=models.CharField(blank=True, db_index=True, help_text="The customer's bill this was stitched against. Readymade work only.", max_length=60),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='job_type',
            field=models.CharField(choices=[('WHOLESALE', 'Wholesale'), ('READYMADE', 'Readymade (against a customer bill)')], default='WHOLESALE', max_length=20),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='photos',
            field=models.TextField(blank=True, help_text="Comma-separated photo paths — the sample or the customer's bill"),
        ),
    ]
