# Generated by Django 6.0.8 on 2026-09-13 06:26

from django.db import migrations, models


def give_every_batch_a_code(apps, schema_editor):
    """
    Nothing can be unique while most rows are blank.

    Batches recorded before the design number existed have none, and an empty
    string collides with every other empty string the moment the constraint
    goes on. Each one gets a code it can be found by: the mill code if it has
    one and that code is still free in its warehouse, otherwise its own batch
    number, which is already unique. Provisional codes are obvious on screen
    and the floor can correct them to the real design number.
    """
    RawClothBatch = apps.get_model("warehouse", "RawClothBatch")

    taken = set()
    for batch in RawClothBatch.objects.all().order_by("pk"):
        current = (batch.design_number or "").strip()
        if current and (current, batch.warehouse_id) not in taken:
            taken.add((current, batch.warehouse_id))
            continue

        code = (batch.cloth_code or "").strip()
        if not code or (code, batch.warehouse_id) in taken:
            code = batch.batch_number

        batch.design_number = code
        batch.save(update_fields=["design_number"])
        taken.add((code, batch.warehouse_id))


def noop(apps, schema_editor):
    """Codes stay. Blanking them would lose numbers people have since typed."""


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0050_stitchingjob_customer_bill_number_and_more'),
    ]

    operations = [
        # Fill every blank before the constraint can possibly hold.
        migrations.RunPython(give_every_batch_a_code, noop),
        migrations.AlterField(
            model_name='rawclothbatch',
            name='design_number',
            field=models.CharField(db_index=True, help_text='The design number this cloth is known by. Unique, and typed by hand.', max_length=60),
        ),
        migrations.AddConstraint(
            model_name='rawclothbatch',
            constraint=models.UniqueConstraint(fields=('design_number', 'warehouse'), name='rawclothbatch_design_number_per_warehouse'),
        ),
    ]
