# Generated by Django 6.0.8 on 2026-09-13 06:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0051_design_number_is_the_cloth_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karigar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=140)),
                ('kind', models.CharField(choices=[('IN_HOUSE', 'In-house'), ('OUTSIDE', 'Outside unit')], default='OUTSIDE', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, help_text='Where the work is done — Mumbai, Surat, local', max_length=80)),
                ('address', models.TextField(blank=True)),
                ('rate_per_piece', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karigar_records', to='warehouse.employeeprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
