# Generated by Django 6.0.8 on 2026-09-13 07:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0052_karigar'),
    ]

    operations = [
        migrations.AddField(
            model_name='stitchingjob',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='karigar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stitching_jobs', to='warehouse.karigar'),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='rate_per_piece',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='stitchingjob',
            name='tailor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TAILOR'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stitching_jobs', to='warehouse.employeeprofile'),
        ),
    ]
