# Generated by Django 6.0.8 on 2026-09-13 11:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0053_stitching_paid_by_the_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingassignment',
            name='cloth_returned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='CuttingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=30)),
                ('target_pieces', models.PositiveIntegerField(default=0)),
                ('pieces_completed', models.PositiveIntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='warehouse.cuttingassignment')),
            ],
            options={
                'ordering': ['sort_order', 'size'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'size'), name='cuttingsize_one_row_per_size')],
            },
        ),
    ]
