# Generated by Django 6.0.8 on 2026-09-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0054_cutting_by_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='StitchingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=30)),
                ('pieces_assigned', models.PositiveIntegerField(default=0)),
                ('pieces_completed', models.PositiveIntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='warehouse.stitchingjob')),
            ],
            options={
                'ordering': ['sort_order', 'size'],
                'constraints': [models.UniqueConstraint(fields=('job', 'size'), name='stitchingsize_one_row_per_size')],
            },
        ),
    ]
