# Generated by Django 6.0.8 on 2026-09-13 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0055_stitching_by_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingassignment',
            name='customer_bill_number',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='cuttingassignment',
            name='job_type',
            field=models.CharField(choices=[('WHOLESALE', 'Wholesale'), ('READYMADE', 'Readymade (against a customer bill)')], default='WHOLESALE', max_length=20),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='issue_lr_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='issue_photos',
            field=models.TextField(blank=True, help_text='Comma-separated photos — usually the LR itself'),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='issue_transporter',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='issue_vehicle_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='return_lr_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='return_photos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='return_transporter',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='return_vehicle_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='return_warehouse',
            field=models.ForeignKey(blank=True, help_text='Where the finished pieces land. Blank means back where the cloth came from.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stitching_returns', to='warehouse.warehouselocation'),
        ),
    ]
