# Generated by Django 6.0.8 on 2026-09-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0056_jobwork_transit'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='customer_bill_number',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
