# Generated by Django 6.0.8 on 2026-09-15 01:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0057_bill_number_reaches_the_garment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobworkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('design_number', models.CharField(blank=True, db_index=True, max_length=60)),
                ('cloth_meters', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cloth_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='What the cloth cost, even though it never came here', max_digits=12)),
                ('job_type', models.CharField(choices=[('WHOLESALE', 'Wholesale'), ('READYMADE', 'Readymade (against a customer bill)')], default='WHOLESALE', max_length=20)),
                ('customer_bill_number', models.CharField(blank=True, db_index=True, max_length=60)),
                ('rate_per_piece', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('SENT', 'Cloth sent'), ('PARTIAL', 'Partly received'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='SENT', max_length=20)),
                ('sent_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('sent_transporter', models.CharField(blank=True, max_length=140)),
                ('sent_lr_number', models.CharField(blank=True, max_length=60)),
                ('sent_vehicle_number', models.CharField(blank=True, max_length=30)),
                ('sent_photos', models.TextField(blank=True, help_text='Comma-separated photos — usually the LR')),
                ('return_transporter', models.CharField(blank=True, max_length=140)),
                ('return_lr_number', models.CharField(blank=True, max_length=60)),
                ('return_vehicle_number', models.CharField(blank=True, max_length=30)),
                ('return_photos', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobwork_orders_created', to=settings.AUTH_USER_MODEL)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobwork_orders', to='warehouse.itemtype')),
                ('karigar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobwork_orders', to='warehouse.karigar')),
                ('receive_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobwork_orders', to='warehouse.warehouselocation')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobwork_orders', to='warehouse.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobworkSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=30)),
                ('pieces_expected', models.PositiveIntegerField(default=0)),
                ('pieces_received', models.PositiveIntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='warehouse.jobworkorder')),
            ],
            options={
                'ordering': ['sort_order', 'size'],
                'constraints': [models.UniqueConstraint(fields=('order', 'size'), name='jobworksize_one_row_per_size')],
            },
        ),
    ]
