# Generated by Django 6.0.8 on 2026-09-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0058_jobwork_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='handed_over_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='handed_over_to',
            field=models.CharField(blank=True, help_text='Who collected it', max_length=140),
        ),
    ]
