# Generated by Django 6.0.8 on 2026-09-15 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0059_readymade_handover'),
    ]

    operations = [
    ]
