# Generated by Django 6.0.8 on 2026-09-15 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0061_backfill_cloth_returned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=140)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('bill_photos', models.TextField(blank=True, help_text='Photos of the written bill')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cuttingassignment',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutting_assignments', to='warehouse.customerorder'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_products', to='warehouse.customerorder'),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobwork_orders', to='warehouse.customerorder'),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stitching_jobs', to='warehouse.customerorder'),
        ),
    ]
