# Generated by Django 6.0.8 on 2026-09-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0063_link_existing_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawclothbatch',
            name='design_number_provisional',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
