# Generated by Django 6.0.8 on 2026-09-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0066_goods_receipt_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobworkorder',
            name='purchase_bill_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobwork_order', to='warehouse.purchasebillitem'),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='deliver_to_karigar',
            field=models.ForeignKey(blank=True, help_text='Set when this cloth went straight to a stitching unit instead of a godown', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchased_cloth', to='warehouse.karigar'),
        ),
    ]
