# Generated by Django 6.0.8 on 2026-10-02 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0067_jobwork_starts_at_the_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='stitchingjob',
            name='design_number',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stitching_jobs', to='warehouse.itemtype'),
        ),
        migrations.AddField(
            model_name='stitchingjob',
            name='purchase_bill_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stitching_job', to='warehouse.purchasebillitem'),
        ),
        migrations.AlterField(
            model_name='stitchingjob',
            name='cutting_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stitching_jobs', to='warehouse.cuttingassignment'),
        ),
    ]
