# Generated by Django 6.0.8 on 2026-10-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0069_outside_jobs_join_the_chain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobworkorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='jobworkorder',
            name='customer_order',
        ),
        migrations.RemoveField(
            model_name='jobworkorder',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='jobworkorder',
            name='karigar',
        ),
        migrations.RemoveField(
            model_name='jobworkorder',
            name='purchase_bill_item',
        ),
        migrations.RemoveField(
            model_name='jobworkorder',
            name='receive_warehouse',
        ),
        migrations.RemoveField(
            model_name='jobworkorder',
            name='supplier',
        ),
        migrations.RemoveConstraint(
            model_name='jobworksize',
            name='jobworksize_one_row_per_size',
        ),
        migrations.RemoveField(
            model_name='jobworksize',
            name='order',
        ),
        migrations.DeleteModel(
            name='JobworkOrder',
        ),
        migrations.DeleteModel(
            name='JobworkSize',
        ),
    ]
