# Generated by Django 6.0.8 on 2026-10-02 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0071_one_answer_to_who_is_stitching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stitchingjob',
            name='tailor',
        ),
    ]
