# Generated by Django 6.0.8 on 2026-10-02 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0076_the_old_shelf_goes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='retaildispatch',
            name='packed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_dispatches_packed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retaildispatch',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_dispatches_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
