# Generated by Django 6.0.8 on 2026-10-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0077_who_closed_the_carton'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailchannel',
            name='api_key',
            field=models.CharField(blank=True, help_text='A key issued by the shop for this warehouse. Used instead of the login when set.', max_length=120),
        ),
    ]
