# Generated by Django 6.0.8 on 2026-10-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0078_the_shop_can_issue_a_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='For GST invoices at the shop.', max_length=20),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='shop_category_id',
            field=models.IntegerField(blank=True, help_text="The category on the shop's site this garment is filed under.", null=True),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='shop_category_name',
            field=models.CharField(blank=True, help_text='Kept only so the warehouse can show the name without asking the shop.', max_length=120),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='shop_channel',
            field=models.CharField(choices=[('BOTH', 'Online and walk-in'), ('ONLINE', 'Online only'), ('WALKIN', 'Walk-in billing only')], default='BOTH', help_text='Where the shop may sell it once it arrives.', max_length=10),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='shop_description',
            field=models.TextField(blank=True, help_text="Shown on the shop's product page."),
        ),
    ]
